# -*- coding: utf-8 -*-
"""EmlLab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16MgSAjRHCw-2ef4jg0h5TWhTyJuawr62

#Week-1
"""

import numpy as np

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

#getting diagonal elements
print(matrix.diagonal())

#printing elements above and below principal diagonal
print(matrix.diagonal(offset=1))
print(matrix.diagonal(offset=-1))

#trace of a matrix
print(matrix.trace())

#eigen values and eigen vectors
eva,eve = np.linalg.eig(matrix)
print(eva)
print(eve)

#dot product of two vectors
v1 = np.array([2,4,3])
v2 = np.array([9,8,6])
print(np.dot(v1,v2))
print(v1@v2)
print(v1*v2)

#addition,subtraction and multiplication of two matrices
m1 = np.array([[1,2,3],[4,5,6],[3,6,9]])
m2 = np.array([[9,8,7],[6,5,4],[3,2,1]])
print(m1+m2) #np.add(m1,m2)
print(m1-m2) #np.subtract(m1,m2)
print(m1*m2)#np.multiply(m1,m2)

"""#Another way"""

print(np.add(m1,m2))
print(np.subtract(m1,m2))
print(np.multiply(m1,m2))



"""#Random values"""

ran = np.random.seed(1)
print(ran)
print(np.random.randint(0,11,3))
print(np.random.randint(0,11,5))
print(np.random.randint(100,size=100))
print(np.random.randint(100,size=5))

#random numbers from array
x=np.random.choice([1,3,5,6])
y=np.random.choice([1,3,5,7,9],size=(2,4))
print(x)
print(y)

np.random.normal(size=(2,3))

"""#Week-2"""

#Creating a DataFrame
import pandas as pd

df = pd.DataFrame(np.random.randn(3,5))
print(df)

